development:
  adapter: postgresql
  encoding: unicode
  database: photogur
  pool: 5
  username: mou_dev
  password:
  gem: 'pg'

test:
  adapter: postgresql
  encoding: unicode
  database: photogur
  pool: 5
  username: mou_dev
  password:
  gem: 'pg'
