# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57c0b68c316f05f50f5d82d66c308d0e7e1f34a779bdb8261ae67836b37a91dfba0b6464777cf670122dfebeba21d520be3e0dc2659390ed76858bb0df267bad

test:
  secret_key_base: e25e2f00181bc51b53ea2b849d35596f140191405adcdd7f75f1295d86d1be10c8a480315c48dd5a2d2885fe20ba04563df4077ada9b9a360385ed860f628baa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
